name: interview-analysis-env
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - conda-forge::pydub
  - pandas
  - scikit-learn=1.1.3
  - opencv
  - nltk
  - notebook
  - conda-forge::gunicorn
  - flask
  - moviepy=1.0.3
  - tensorflow
  - conda-forge::keras=2.13.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - assemblyai==0.37.0
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - facenet-pytorch==2.6.0
      - fer==22.5.1
      - ffmpeg==1.4
      - filelock==3.17.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - keras==3.9.0
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - namex==0.0.8
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - opencv-contrib-python==4.11.0.86
      - optree==0.14.1
      - pillow==10.2.0
      - praat-parselmouth==0.4.5
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.2.1
      - python-dotenv==1.0.1
      - sniffio==1.3.1
      - sympy==1.13.3
      - torch==2.2.2
      - torchvision==0.17.2
      - triton==2.2.0
      - websockets==15.0.1

